% -------------------------------------------------------------------
%  Generated by MATLAB on 14-Oct-2019 17:52:42
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('saved.mat');

Model_Mapping_workspace = 1;

base = '/Volumes/Macintosh data/lpellis/Desktop/model-mapping-github/';

current_dir = ['/Volumes/Macintosh data/lpellis/Desktop/model-mapping-g' ...
               'ithub'];

differences = saveVarsMat.differences; % <1x1 struct> too many elements at differences.NGM_G_stored

filename = ['R015_pAA00_05_95_psi10_02_40_phi10_theta02_gammaG100_H100_' ...
            '100sim_e5_init050'];

fo = ['/Volumes/Macintosh data/lpellis/Desktop/model-mapping-github/out' ...
      'put-workspaces/GB/R015_pAA00_05_95_psi10_02_40_phi10_theta02_gam' ...
      'maG100_H100_100sim_e5_init050.mat'];

folder = '-workspaces/';

fs = ['/Volumes/Macintosh data/lpellis/Desktop/model-mapping-github/sav' ...
      'ed-workspaces/GB/R015_pAA00_05_95_psi10_02_40_phi10_theta02_gamm' ...
      'aG100_H100_100sim_e5_init050.mat'];

ft = ['/Volumes/Macintosh data/lpellis/Desktop/model-mapping-github/too' ...
      'ls/'];

output_workspace = saveVarsMat.output_workspace; % <1x1 struct> memory allocation error when processing output_workspace.labels

saved_workspace = saveVarsMat.saved_workspace; % <1x1 struct> too many elements at saved_workspace.NGM_A_stored

subfolder = 'GB';

clear saveVarsMat;
